services:
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: Europe/Warsaw
    container_name: company-php
    volumes:
      - ./:/app
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
      - php_composer_data:/root/.composer
    networks:
      - sandbox-network
      
  company-www:
    build: ./docker/www
    container_name: company-www
    ports:
      - 8083:80
    volumes:
      - ./:/app
      - ./docker/www/conf.d:/etc/nginx/conf.d
    networks:
      - sandbox-network

  company-db:
    build:
      context: ./docker/postgres
    container_name: company-db
    environment:
      - POSTGRES_USER=company
      - POSTGRES_PASSWORD=company
      - POSTGRES_DB=company
    volumes:
      - company_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - sandbox-network
    command:
      - postgres
      - -c
      - ssl=on
      - -c
      - ssl_cert_file=/var/lib/postgresql/certs/server.crt
      - -c
      - ssl_key_file=/var/lib/postgresql/certs/server.key
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U company"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  company_db_data:
  php_composer_data:

networks:
  sandbox-network:
    external: true
    name: sandbox-network
